name: CI/CD TrainBook Deployment to Multiple Environments

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Validate with Maven
        run: mvn validate

      - name: Compile with Maven
        run: mvn compile

      - name: Test with Maven
        run: mvn test

      - name: Package with Maven
        run: mvn package

      - name: Deploy to Dev
        run: |
          curl -v --fail -u "${{ secrets.TOMCAT_DEV_USER }}:${{ secrets.TOMCAT_DEV_PASSWORD }}" \
          -T target/TrainBook-1.0.0-SNAPSHOT.war \
          "http://${{ secrets.TOMCAT_DEV_HOST }}/manager/text/deploy?path=/TrainBook&update=true"

      - name: Deploy to Test
        run: |
          curl -v --fail -u "${{ secrets.TOMCAT_TEST_USER }}:${{ secrets.TOMCAT_TEST_PASSWORD }}" \
          -T target/TrainBook-1.0.0-SNAPSHOT.war \
          "http://${{ secrets.TOMCAT_TEST_HOST }}/manager/text/deploy?path=/TrainBook&update=true"

      - name: Deploy to Pre-Prod
        run: |
          curl -v --fail -u "${{ secrets.TOMCAT_PREPROD_USER }}:${{ secrets.TOMCAT_PREPROD_PASSWORD }}" \
          -T target/TrainBook-1.0.0-SNAPSHOT.war \
          "http://${{ secrets.TOMCAT_PREPROD_HOST }}/manager/text/deploy?path=/TrainBook&update=true"

      - name: Deploy to Prod
        run: |
          curl -v --fail -u "${{ secrets.TOMCAT_PROD_USER }}:${{ secrets.TOMCAT_PROD_PASSWORD }}" \
          -T target/TrainBook-1.0.0-SNAPSHOT.war \
          "http://${{ secrets.TOMCAT_PROD_HOST }}/manager/text/deploy?path=/TrainBook&update=true"